### ISSUE TITLE
Enhance Robustness of _format_nodes in Graph Transformers

### ISSUE THREAD

**Issue by namtran6701** [langchain-ai/langchain-experimental#10]
**Description:**  
When using the `LLMGraphTransformer` with certain LLMs (e.g., Ollama), we encountered `ValidationError`s due to nodes with `None` types. The current implementation of `_format_nodes` in `langchain_experimental/graph_transformers/llm.py` permits `None` as a node type, which conflicts with the `Node` model that expects a string.

**Current Implementation:**
```python
def _format_nodes(nodes: List[Node]) -> List[Node]:
    return [
        Node(
            id=el.id.title() if isinstance(el.id, str) else el.id,
            type=el.type.capitalize()  # type: ignore[arg-type]
            if el.type
            else None,  # handle empty strings  # type: ignore[arg-type]
            properties=el.properties,
        )
        for el in nodes
    ]
```

This can lead to the following error when a node has a `None` type:
```
ValidationError: Input should be a valid string
```

---

**Proposed Solution:**  

Modify `_format_nodes` to handle `None` types more robustly, preventing `ValidationError`s and ensuring graph consistency.

**Proposed Change:**
```python
def _format_nodes(nodes: List[Node], default_type: str = "Unknown") -> List[Node]:
    return [
        Node(
            id=el.id.title() if isinstance(el.id, str) else el.id,
            type=el.type.capitalize() if el.type else default_type,
            properties=el.properties,
        )
        for el in nodes
    ]
```

**Key Improvements:**
1. Makes sure the node type always returns a valid string, preventing `ValidationError`s.
2. Introduces a customizable `default_type` parameter (defaulting to "Unknown").
3. Maintains backwards compatibility 

---

**Benefits:**
- Prevents errors when working with LLMs that return incomplete node data.
- Graphs don’t fail due to missing type information.
- Allows custom default behavior for node types via the `default_type` parameter.

---

**Potential Concerns:**
- Changes default behavior slightly, potentially impacting implementations relying on `None` types.
- Might hide data quality issues that the current behavior exposes.
---

**Comment by tomasonjo** [comment]
I think this was fixed in previous commit: https://github.com/langchain-ai/langchain-experimental/commit/6fdfdbe2d66325a2e81555890715e69946e7e26b

**Comment by namtran6701** [comment]
I actually encountered that issued after the commit

**Comment by tomasonjo** [comment]
Yeah, commit is in, but there was no new release after unfortunately

**Comment by namtran6701** [comment]
aight I see
